### ISSUE TITLE
Remove `requirements.yml` from template

### ISSUE THREAD

**Issue by p-j-smith** [UCL-MIRSG/mirsg-template#10]
### Short Description

The template contains a `requirements.yml`, which suggests using it for creating an Ansible role / collection. We could either use the official template for Ansible Collections (https://github.com/ansible-collections/collection_template), or create our own under `UCL-ARC` with molecule testing and github workflows set up.

**Comment by paddyroddy** [comment]
You can remove the `requirements.yml` if you feel it is inappropriate - but I would argue we still need the template. It may seem obvious to us, but it's really good if we can include `pre-commit` & @renovatebot + CI in all new repos.

**Comment by paddyroddy** [comment]
I think I included it just to make this work https://github.com/UCL-MIRSG/mirsg-template/blob/bcb69aae88e44931e1ea9a9af143ee4378a971e3/.github/workflows/linting.yml#L29 which obviously is silly in this example

**Comment by p-j-smith** [comment]
> I would argue we still need the template. It may seem obvious to us, but it's really good if we can include pre-commit & https://github.com/renovatebot + CI in all new repos.

Yeah that's true. Even if a new repo is created using a different template, it's still useful to be able to copy these files quickly from this repo

> I think I included it just to make this work

I think that `ansible-roles-config` (and `requirements.yml`) can be removed from this repo now that [the default is `missing`](https://github.com/UCL-MIRSG/.github/blob/a07c94781c629100f92dd70cc309d87ac3baace3/actions/linting/action.yml#L6-L8)

**Comment by paddyroddy** [comment]
> I think that `ansible-roles-config` (and `requirements.yml`) can be removed from this repo now that [the default is `missing`](https://github.com/UCL-MIRSG/.github/blob/a07c94781c629100f92dd70cc309d87ac3baace3/actions/linting/action.yml#L6-L8)

Agreed. The default was actually always `missing`, I think I just did it in case people didn't know how to lint with `ansible`. But it probably causes more confusion than it solves.
